kind: pipeline
name: clock
type: ssh

server:
  host: clock.lan
  user: pi
  ssh_key:
    from_secret: ssh_key

steps:
- name: get deps
  commands:
    - go get -d

- name: test
  commands:      
    - go test
    - go test -race
    - go test -cover
    - go test -bench=.

- name: build
  commands:
    - go build

- name: deploy
  commands:      
  - cp ./sdl-clock /home/pi/sdl-clock/sdl-clock
  - sudo systemctl restart clockgo.service

- name: notify
  image: plugins/pushover
  settings:
    user:
      from_secret: pushover_user
    token:
      from_secret: pushover_token
  when:
    status:
    - success
    - failure
 