kind: pipeline
name: clock

steps:
- name: get deps
  image: golang
  volumes:
    - name: deps
      path: /go
  commands:
    - go get -d

- name: test
  image: golang
  volumes:
    - name: deps
      path: /go
  commands:      
    - go test
    - go test -race
    - go test -cover
    - go test -bench=.

- name: build
  image: golang
  volumes:
    - name: deps
      path: /go
  commands:
    - go build

- name: deploy
  image: alpine
  environment:
    DEPLOY_HOST: 'pi@clock.lan'
    SSH_KEY:
      from_secret: ssh_key
  commands:      
  - mkdir $HOME/.ssh
  - echo "$SSH_KEY" > $HOME/.ssh/id_ed25519
  - chmod 600 $HOME/.ssh/id_ed25519
  - apk add --no-cache openssh
  - ssh-keyscan -H bob.jba.io > $HOME/.ssh/known_hosts  
  - ssh-keyscan -H git.jba.io >> $HOME/.ssh/known_hosts 
  - scp sdl-clock $DEPLOY_HOST:/home/pi/sdl-clock/
  - ssh $DEPLOY_HOST sudo systemctl restart clockgo.service

- name: notify
  image: plugins/pushover
  settings:
    user:
      from_secret: pushover_user
    token:
      from_secret: pushover_token
  when:
    status:
    - success
    - failure

volumes:
  - name: deps
    temp: {}  