kind: pipeline
name: clock
type: ssh

server:
  host: clock.lan
  user: pi
  ssh_key:
    from_secret: ssh_key

steps:
- name: get deps
  commands:
    - export PATH=$PATH:/usr/local/go/bin
    - go get -d

#- name: test
#  commands:     
#    - export PATH=$PATH:/usr/local/go/bin   
#    - go test
#    - go test -cover
#    - go test -bench=.

- name: build
  commands:
    - export PATH=$PATH:/usr/local/go/bin  
    - go build

- name: deploy
  commands:    
  - sudo systemctl stop clockgo.service  
  - cp ./sdl-clock /home/pi/sdl-clock/sdl-clock
  - sudo systemctl start clockgo.service

- name: notify
  image: plugins/pushover
  settings:
    user:
      from_secret: pushover_user
    token:
      from_secret: pushover_token
  when:
    status:
    - success
    - failure
 